version: '3.5'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: storage
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

